import type { Drama } from '@/types'

const ep = (n: number) =>
  Array.from({ length: n }, (_, i) => ({
    id: String(i + 1),
    title: `Episódio ${i + 1}`,
    ytId: 'dQw4w9WgXcQ',
    free: i < 2,
    order: i + 1,
  }))

export const DRAMAS: (Drama & { icon: string })[] = [
  {
    id:'1', title:'Amor em Segredo', genre:'romance',
    description:'Dois jovens apaixonam-se em circunstâncias impossíveis. Uma história de amor intensa em episódios de 90 segundos.',
    short:'Amor impossível em 90 segundos.',
    status:'Ativo', rating:4.9, views:2100000, year:2025, episodes:ep(8),
    posterGrad:'var(--rs-poster-romance)', badge:'NOVO',
    cast:['Aida Pereira','Mário do Rosário','Helga Freitas'],
    icon:'&#128149;',
  },
  {
    id:'2', title:'O Herdeiro', genre:'corporativo',
    description:'O herdeiro de um império descobre traições na família. Cada episódio revela um novo segredo explosivo.',
    short:'Império. Traição. Vingança.',
    status:'Ativo', rating:4.9, views:2300000, year:2025, episodes:ep(10),
    posterGrad:'var(--rs-poster-corporate)', badge:'TOP',
    cast:['Beto Quissua','Nuno Maló','Isabel Tomásia'],
    icon:'&#128084;',
  },
  {
    id:'3', title:'Segredos da Noite', genre:'suspense',
    description:'Um detetive investiga crimes misteriosos a meia-noite. A verdade está mais perto do que parece.',
    short:'Cada crime, um segredo.',
    status:'Ativo', rating:4.7, views:980000, year:2025, episodes:ep(6),
    posterGrad:'var(--rs-poster-suspense)', badge:'HOT',
    cast:['Élio Cunha','Cláudia Mussunda'],
    icon:'&#128270;',
  },
  {
    id:'4', title:'Rindo Sempre', genre:'comedia',
    description:'Um comediante tenta sobreviver ao dia a dia caótico da vida moderna em Angola.',
    short:'A vida é uma piada.',
    status:'Ativo', rating:4.6, views:1200000, year:2024, episodes:ep(12),
    posterGrad:'var(--rs-poster-comedy)', badge:'NOVO',
    cast:['Júlio dos Santos','Magda Pondja'],
    icon:'&#127908;',
  },
  {
    id:'5', title:'Casa Assombrada', genre:'terror',
    description:'Uma família muda-se para uma casa com segredos sombrios. Nem tudo é o que parece nesta história.',
    short:'A casa nunca esqueceu.',
    status:'Ativo', rating:4.5, views:760000, year:2025, episodes:ep(8),
    posterGrad:'var(--rs-poster-horror)', badge:'NOVO',
    cast:['Rita Bessa','Carlos André'],
    icon:'&#128123;',
  },
  {
    id:'6', title:'Duelo de Espadas', genre:'acao',
    description:'Dois guerreiros rivais lutam pelo amor de uma princesa. Acção e romance num mesmo drama explosivo.',
    short:'O aço fala. O amor sangra.',
    status:'Ativo', rating:4.8, views:1500000, year:2024, episodes:ep(14),
    posterGrad:'var(--rs-poster-action)', badge:undefined,
    cast:['Pedro Quitumba','Helena Lobito'],
    icon:'&#9876;',
  },
  {
    id:'7', title:'CEO Apaixonado', genre:'corporativo',
    description:'O CEO mais temido apaixona-se pela sua assistente. Uma história proibida que vai mudar tudo.',
    short:'Ele controla tudo. Menos o coração.',
    status:'Ativo', rating:5.0, views:3100000, year:2026, episodes:ep(16),
    posterGrad:'var(--rs-poster-corporate-2)', badge:'EXCLUSIVO',
    cast:['Tiago Bumba','Sofia Cassule'],
    icon:'&#128084;',
  },
  {
    id:'8', title:'A Maldição', genre:'terror',
    description:'Uma maldição antiga assombra uma pequena cidade. Poucos sobrevivem a descobrir a verdade.',
    short:'O passado nunca morre.',
    status:'Ativo', rating:4.7, views:1100000, year:2025, episodes:ep(6),
    posterGrad:'var(--rs-poster-horror-2)', badge:'HOT',
    cast:['Margarida Calembe'],
    icon:'&#128123;',
  },
  {
    id:'9', title:'Primeiro Beijo', genre:'romance',
    description:'Dois vizinhos descobrem os seus sentimentos aos poucos. Uma história doce e inesquecível.',
    short:'O amor mora ao lado.',
    status:'Ativo', rating:4.4, views:640000, year:2025, episodes:ep(8),
    posterGrad:'var(--rs-poster-romance-2)', badge:'NOVO',
    cast:['Diana Sangengo','Bruno Ekuikui'],
    icon:'&#127801;',
  },
  {
    id:'10', title:'Ninja Moderno', genre:'acao',
    description:'Um ninja tenta adaptar-se à vida moderna sem revelar os seus poderes secretos.',
    short:'Espadas antigas, metro novo.',
    status:'Ativo', rating:4.8, views:1900000, year:2024, episodes:ep(12),
    posterGrad:'var(--rs-poster-action-2)', badge:'TOP',
    cast:['Kassindja Lutas'],
    icon:'&#9876;',
  },
  {
    id:'11', title:'Traição', genre:'suspense',
    description:'Uma esposa descobre a dupla vida do marido. A verdade vem sempre ao de cima neste thriller intenso.',
    short:'Tudo o que ele esconde.',
    status:'Ativo', rating:4.6, views:890000, year:2025, episodes:ep(10),
    posterGrad:'var(--rs-poster-suspense-2)', badge:undefined,
    cast:['Vera Tati','Edmilson Bambi'],
    icon:'&#128270;',
  },
  {
    id:'12', title:'Stand Up de Luxo', genre:'comedia',
    description:'Um comediante falido tenta estrear-se no mundo do luxo com resultados hilariantes.',
    short:'Rir é caro.',
    status:'Ativo', rating:4.3, views:420000, year:2026, episodes:ep(8),
    posterGrad:'var(--rs-poster-comedy-2)', badge:'NOVO',
    cast:['Hilário Massembe'],
    icon:'&#127908;',
  },
]

export const BADGE_STYLE: Record<string, React.CSSProperties> = {
  'NOVO':      { background: 'var(--rs-badge-novo-bg)', color: '#fff' },
  'HOT':       { background: 'var(--rs-hot)', color: '#fff' },
  'TOP':       { background: '#fff', color: '#000' },
  'EXCLUSIVO': { background: 'var(--rs-accent)', color: '#000' },
}
